# Generated by Django 5.0.2 on 2024-02-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="leaving_date",
            field=models.DateField(blank=True),
        ),
    ]
